# Copyright (c) OpenMMLab. All rights reserved.
runner = dict(
    name='Gesture Recognition',
    camera_id=0,
    camera_fps=15,
    synchronous=False,
    buffer_sizes=dict(_input_=20, det_result=10),
    nodes=[
        dict(
            type='MultiFrameDetectorNode',
            name='Detector',
            model_config='demo/mmdetection_cfg/'
            'ssdlite_mobilenetv2_scratch_600e_onehand.py',
            model_checkpoint='https://download.openmmlab.com/mmpose/'
            'mmdet_pretrained/'
            'ssdlite_mobilenetv2_scratch_600e_onehand-4f9f8686_20220523.pth',
            device='cpu',
            inference_frame='last',
            input_buffer='_input_',
            output_buffer='det_result'),
        dict(
            type='HandGestureRecognizerNode',
            name='GestureRecognizer',
            model_config='configs/hand/gesture_sview_rgbd_vid/mtut/'
            'nvgesture/i3d_nvgesture_bbox_112x112_fps15_rgb.py',
            model_checkpoint='https://download.openmmlab.com/mmpose/'
            'gesture/mtut/i3d_nvgesture/'
            'i3d_nvgesture_bbox_112x112_fps15-363b5956_20220530.pth',
            device='cpu',
            input_buffer='det_result',
            output_buffer='gesture',
            fps=15,
            score_thr=0.7),
        dict(
            type='ModelResultBindingNode',
            name='ResultBinder',
            frame_buffer='_frame_',
            result_buffer='gesture',
            output_buffer='frame'),
        dict(
            type='GestureVisualizerNode',
            name='Visualizer',
            enable_key='v',
            frame_buffer='frame',
            output_buffer='vis'),
        dict(
            type='MonitorNode',
            name='Monitor',
            enable_key='m',
            enable=False,
            frame_buffer='vis',
            output_buffer='display'),
        dict(
            type='RecorderNode',
            name='Recorder',
            out_video_file='record.mp4',
            frame_buffer='display',
            output_buffer='_display_')
    ])
