version: 2

formats:
  - epub

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

sphinx:
  configuration: docs/zh_cn/conf.py

python:
  install:
    - requirements: requirements/docs.txt
    - requirements: requirements/readthedocs.txt
